<template><div><h1 id="基本数据类型转换" tabindex="-1"><a class="header-anchor" href="#基本数据类型转换" aria-hidden="true">#</a> 基本数据类型转换</h1>
<!-- more -->
<h2 id="自动类型转换" tabindex="-1"><a class="header-anchor" href="#自动类型转换" aria-hidden="true">#</a> 自动类型转换</h2>
<h3 id="介绍" tabindex="-1"><a class="header-anchor" href="#介绍" aria-hidden="true">#</a> 介绍:</h3>
<p>​      当iava程序在进行赋值或者运算时，精度小的类型自动转换为精度大的数据类型这个就是自动类型转换。</p>
<p>​      数据类型按精度(容量)大小排序为(背，规则)</p>
<figure><img src="@source/learning-notes/java/primary/image/11.png" alt="image-20230224003002648" tabindex="0" loading="lazy"><figcaption>image-20230224003002648</figcaption></figure>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">public</span><span style="color: #E06C75"> </span><span style="color: #C678DD">class</span><span style="color: #E06C75"> </span><span style="color: #E5C07B">AutoConvert</span><span style="color: #E06C75"> </span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #E06C75">    </span><span style="color: #C678DD">public</span><span style="color: #61AFEF"> </span><span style="color: #C678DD">static</span><span style="color: #61AFEF"> </span><span style="color: #C678DD">void</span><span style="color: #61AFEF"> main</span><span style="color: #ABB2BF">(</span><span style="color: #E5C07B">String</span><span style="color: #ABB2BF">[] </span><span style="color: #E06C75; font-style: italic">args</span><span style="color: #ABB2BF">)</span><span style="color: #61AFEF"> </span><span style="color: #ABB2BF">{</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #C678DD">int</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">num</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;a&#39;</span><span style="color: #ABB2BF">; </span><span style="color: #7F848E; font-style: italic">//ok char -&gt; int</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #C678DD">double</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">d1</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">80</span><span style="color: #ABB2BF">; </span><span style="color: #7F848E; font-style: italic">//ok int -&gt; doublre</span></span>
<span class="line"><span style="color: #ABB2BF">    	</span><span style="color: #E5C07B">System</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">out</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">println</span><span style="color: #ABB2BF">(num); </span><span style="color: #7F848E; font-style: italic">//97</span></span>
<span class="line"><span style="color: #ABB2BF">    	</span><span style="color: #E5C07B">System</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">out</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">printIn</span><span style="color: #ABB2BF">(d1); </span><span style="color: #7F848E; font-style: italic">//80.0</span></span>
<span class="line"><span style="color: #ABB2BF">      }</span></span>
<span class="line"><span style="color: #E06C75"> </span><span style="color: #ABB2BF">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="自动类型转换注意和细节" tabindex="-1"><a class="header-anchor" href="#自动类型转换注意和细节" aria-hidden="true">#</a> 自动类型转换注意和细节</h3>
<p>​	1.有多种类型的数据混合运算时，系统首先自动将所有数据转换成容量最大的那种数据类型，然后再进行计算</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #E06C75">        </span><span style="color: #C678DD">int</span><span style="color: #E06C75"> n1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">10</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">//ok</span></span>
<span class="line"><span style="color: #E06C75">        </span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #7F848E; font-style: italic">//错误 n1 + 1.1 =&gt; 结果类型是 double</span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #C678DD">float</span><span style="color: #E06C75"> d1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> n1 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.1</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span></span>
<span class="line"><span style="color: #E06C75">        </span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #7F848E; font-style: italic">//对 n1 + 1.1 =&gt; 结果类型是 doubledouble</span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #C678DD">double</span><span style="color: #E06C75"> d1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> n1 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.1</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span></span>
<span class="line"><span style="color: #E06C75">        </span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #7F848E; font-style: italic">//对 n1 + 1.1 =&gt; 结果类型是 float</span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #C678DD">float</span><span style="color: #E06C75"> d1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> n1 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.1F</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>​	2.当我们把精度(容量)大 的数据类型赋值给精度(容量)小 的数据类型时，就会报错，反之就会进行自动类型转换</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #E06C75">         </span><span style="color: #7F848E; font-style: italic">//错误 double -&gt; int</span></span>
<span class="line"><span style="color: #E06C75">         </span><span style="color: #C678DD">int</span><span style="color: #E06C75"> n2 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.1</span><span style="color: #ABB2BF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>​	3.<strong>(byte,short)</strong> 和 <strong>char</strong> 之间不会相互自动转换</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">       /** </span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">        * 当把具体数赋给 byte 时，(1)先判断该数是否在byte范围内，如果是就可以</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">        */</span></span>
<span class="line"><span style="color: #E06C75">        </span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #7F848E; font-style: italic">//对  -128-127</span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #C678DD">byte</span><span style="color: #E06C75"> b1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">10</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span></span>
<span class="line"><span style="color: #E06C75">        </span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #7F848E; font-style: italic">// int n2 = 1; //n2 是int</span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #7F848E; font-style: italic">// byte b2 = n2; //错误，原因 : 如果是变量赋值，判断类型</span></span>
<span class="line"><span style="color: #E06C75">        </span></span>
<span class="line"><span style="color: #E06C75">        </span><span style="color: #7F848E; font-style: italic">//错误， 原因 byte 不能自动转成 char</span></span>
<span class="line"><span style="color: #E06C75">         </span><span style="color: #C678DD">char</span><span style="color: #E06C75"> c1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> b1</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>​	4.byte，short，char 他们三者可以计算，在计算时首先转换为 int 类型</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">byte</span><span style="color: #E06C75"> b2 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">byte</span><span style="color: #E06C75"> b3 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">2</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">short</span><span style="color: #E06C75"> s1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1</span><span style="color: #ABB2BF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 错 b2 + s1 =&gt; int</span></span>
<span class="line"><span style="color: #C678DD">short</span><span style="color: #E06C75"> s2 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> b2 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> s1 </span></span>
<span class="line"><span style="color: #E06C75">    </span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 对 b2 + s1 =&gt; int</span></span>
<span class="line"><span style="color: #E06C75"> </span><span style="color: #C678DD">int</span><span style="color: #E06C75"> s2 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> b2 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> s1</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 错 b2 + b3 =&gt; int</span></span>
<span class="line"><span style="color: #C678DD">byte</span><span style="color: #E06C75"> b4 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> b2 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> b3</span><span style="color: #ABB2BF">;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>​	5.boolean 不参与转换</p>
<p>​	6.自动提升原则: 表达式结果的类型自动提升为 操作数中最大的类型</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">byte</span><span style="color: #E06C75"> b4 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">short</span><span style="color: #E06C75"> s3 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">100</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">int</span><span style="color: #E06C75"> num1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.1</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">double</span><span style="color: #E06C75"> num2 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.1</span><span style="color: #ABB2BF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">double</span><span style="color: #E06C75"> num3 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> b4 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> s3 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> num1 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> num2</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #C678DD">float</span><span style="color: #E06C75"> num4 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> b4 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> s3 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> num1 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> num2</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="强制类型转换" tabindex="-1"><a class="header-anchor" href="#强制类型转换" aria-hidden="true">#</a> 强制类型转换</h2>
<h4 id="介绍-1" tabindex="-1"><a class="header-anchor" href="#介绍-1" aria-hidden="true">#</a> 介绍 ：</h4>
<h5 id="自动类型转换的逆过程-将容量大的数据类型转换为容量小的数据类型。使用时要加上强制转换符-但可能造成精度降低或溢出-格外要注意。" tabindex="-1"><a class="header-anchor" href="#自动类型转换的逆过程-将容量大的数据类型转换为容量小的数据类型。使用时要加上强制转换符-但可能造成精度降低或溢出-格外要注意。" aria-hidden="true">#</a> 自动类型转换的逆过程，将<strong>容量大</strong>的数据类型<strong>转换</strong>为<strong>容量小</strong>的数据类型。使用时要加上强制<strong>转换符()</strong>，但可能造成<strong>精度降低或溢出</strong>,格外要注意。</h5>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// 造成精度损失</span></span>
<span class="line"><span style="color: #C678DD">int</span><span style="color: #E06C75"> n1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> (</span><span style="color: #C678DD">int</span><span style="color: #E06C75">)</span><span style="color: #D19A66">1.9</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #E5C07B">System</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">out</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">println</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&quot;n1=&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">+</span><span style="color: #ABB2BF"> n1);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 造成数据溢出</span></span>
<span class="line"><span style="color: #C678DD">int</span><span style="color: #E06C75"> n2 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">2000</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">byte</span><span style="color: #E06C75"> b1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> (</span><span style="color: #C678DD">byte</span><span style="color: #E06C75">)n2</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #E5C07B">System</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">out</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">println</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&quot;b1=&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">+</span><span style="color: #ABB2BF"> b1);</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="细节说明" tabindex="-1"><a class="header-anchor" href="#细节说明" aria-hidden="true">#</a> 细节说明</h4>
<ol>
<li>
<p>​	当进行数据的大小从  大 ——&gt; 小，就需要使用到强制转换</p>
</li>
<li>
<p>强制转换符号只正对最近的操作符有效，使用小括号提升优先级</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #7F848E; font-style: italic">// 错误</span></span>
<span class="line"><span style="color: #C678DD">int</span><span style="color: #E06C75"> x </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> (</span><span style="color: #C678DD">int</span><span style="color: #E06C75">)</span><span style="color: #D19A66">10</span><span style="color: #E06C75"> </span><span style="color: #56B6C2">*</span><span style="color: #E06C75"> </span><span style="color: #D19A66">3.5</span><span style="color: #E06C75"> </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #D19A66">6</span><span style="color: #E06C75"> </span><span style="color: #56B6C2">*</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.5</span></span>
<span class="line"><span style="color: #E06C75">    </span></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 正确</span></span>
<span class="line"><span style="color: #E06C75"> </span><span style="color: #C678DD">int</span><span style="color: #E06C75"> y </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> (</span><span style="color: #C678DD">int</span><span style="color: #E06C75">)(</span><span style="color: #D19A66">10</span><span style="color: #E06C75"> </span><span style="color: #56B6C2">*</span><span style="color: #E06C75"> </span><span style="color: #D19A66">3.5</span><span style="color: #E06C75"> </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #D19A66">6</span><span style="color: #E06C75"> </span><span style="color: #56B6C2">*</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.5</span><span style="color: #E06C75">)</span><span style="color: #D19A66">10</span><span style="color: #E06C75"> </span><span style="color: #56B6C2">*</span><span style="color: #E06C75"> </span><span style="color: #D19A66">3.5</span><span style="color: #E06C75"> </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #D19A66">6</span><span style="color: #E06C75"> </span><span style="color: #56B6C2">*</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.5</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>char 类型可以保存 int 的常量直值，但不能保存 int 的变量值，需要强制转换</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">char</span><span style="color: #E06C75"> a </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">100</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span></span>
<span class="line"><span style="color: #C678DD">int</span><span style="color: #E06C75"> b </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">100</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #C678DD">char</span><span style="color: #E06C75"> c </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> a</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 错</span></span>
<span class="line"><span style="color: #C678DD">char</span><span style="color: #E06C75"> m </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> (</span><span style="color: #C678DD">char</span><span style="color: #E06C75">)b</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #E5C07B">System</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">out</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">println</span><span style="color: #ABB2BF">(m);</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>byte 和 short，char 类型在进行运算时，当做 int 类型来处理</p>
</li>
</ol>
<h2 id="基本数据类型的转换练习" tabindex="-1"><a class="header-anchor" href="#基本数据类型的转换练习" aria-hidden="true">#</a> 基本数据类型的转换练习</h2>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">short</span><span style="color: #E06C75"> s </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">12</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #E06C75">s </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> s </span><span style="color: #56B6C2">-</span><span style="color: #E06C75"> </span><span style="color: #D19A66">9</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 错 int ---&gt; short</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">byte</span><span style="color: #E06C75"> b </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">10</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #E06C75">b </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> b </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #D19A66">11</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 错 int ---&gt; byte</span></span>
<span class="line"><span style="color: #E06C75">b </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> (</span><span style="color: #C678DD">byte</span><span style="color: #E06C75">)(b </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1</span><span style="color: #E06C75">)</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对 使用强转</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">char</span><span style="color: #E06C75"> c </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #98C379">&#39;a&#39;</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #C678DD">int</span><span style="color: #E06C75"> i </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">16</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #C678DD">float</span><span style="color: #E06C75"> d </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">.314F</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #C678DD">double</span><span style="color: #E06C75"> resule </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> c </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> i </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> d</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对 float ---&gt; double</span></span>
<span class="line"></span>
<span class="line"><span style="color: #C678DD">byte</span><span style="color: #E06C75"> b </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">16</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #C678DD">short</span><span style="color: #E06C75"> s </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">14</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 对</span></span>
<span class="line"><span style="color: #C678DD">short</span><span style="color: #E06C75"> t </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> s </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> b</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 错误 int ---&gt; short</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="基本数据类型和string-类型的转换" tabindex="-1"><a class="header-anchor" href="#基本数据类型和string-类型的转换" aria-hidden="true">#</a> 基本数据类型和<strong>String</strong> 类型的转换</h2>
<h3 id="介绍-2" tabindex="-1"><a class="header-anchor" href="#介绍-2" aria-hidden="true">#</a> 介绍</h3>
<p>​	在程序开发中，我们经常需要将基本数据类型转成 <strong>String</strong>  类型。或者将<strong>String</strong> 型转成<strong>基本数据类型</strong>。</p>
<h3 id="基本类型转-string-类型" tabindex="-1"><a class="header-anchor" href="#基本类型转-string-类型" aria-hidden="true">#</a> 基本类型转 <strong>String</strong> 类型</h3>
<p><strong>语法：</strong> 将基本类型的值 + &quot;&quot; 即可</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #C678DD">int</span><span style="color: #E06C75"> n1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">100</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">float</span><span style="color: #E06C75"> n2 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">1.1F</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">double</span><span style="color: #E06C75"> n3 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">4.5</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #C678DD">boolean</span><span style="color: #E06C75"> n4 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">// 转换为 String 类型</span></span>
<span class="line"><span style="color: #E5C07B">String</span><span style="color: #E06C75"> s1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> n1 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #98C379">&quot;&quot;</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #E5C07B">String</span><span style="color: #E06C75"> s2 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> n2 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #98C379">&quot;&quot;</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #E5C07B">String</span><span style="color: #E06C75"> s3 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> n3 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #98C379">&quot;&quot;</span><span style="color: #ABB2BF">;</span></span>
<span class="line"><span style="color: #E5C07B">String</span><span style="color: #E06C75"> s4 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> n4 </span><span style="color: #56B6C2">+</span><span style="color: #E06C75"> </span><span style="color: #98C379">&quot;&quot;</span><span style="color: #ABB2BF">;</span><span style="color: #E06C75">    </span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="string类型转基本数据类型" tabindex="-1"><a class="header-anchor" href="#string类型转基本数据类型" aria-hidden="true">#</a> String类型转基本数据类型</h3>
<p><strong>语法：</strong> 通过基本类型的包装类调用parseXX方法即可</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #E5C07B">String</span><span style="color: #E06C75"> str </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #98C379">&quot;123456&quot;</span><span style="color: #ABB2BF">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #7F848E; font-style: italic">//转换 str 为其他数据类型</span></span>
<span class="line"><span style="color: #C678DD">int</span><span style="color: #E06C75"> a1 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #E5C07B">Integer</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">parseInt</span><span style="color: #ABB2BF">(str);</span></span>
<span class="line"><span style="color: #C678DD">double</span><span style="color: #E06C75"> a2 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #E5C07B">Double</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">parseDouble</span><span style="color: #ABB2BF">(str);</span></span>
<span class="line"><span style="color: #C678DD">float</span><span style="color: #E06C75"> a3 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #E5C07B">Float</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">parseFloat</span><span style="color: #ABB2BF">(str);</span></span>
<span class="line"><span style="color: #C678DD">long</span><span style="color: #E06C75"> a4 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #E5C07B">Long</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">parseLong</span><span style="color: #ABB2BF">(str);</span></span>
<span class="line"><span style="color: #C678DD">byte</span><span style="color: #E06C75"> a5 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #E5C07B">Byte</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">parseByte</span><span style="color: #ABB2BF">(str);</span></span>
<span class="line"><span style="color: #C678DD">boolean</span><span style="color: #E06C75"> a6 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #E5C07B">Boolean</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">parseBoolean</span><span style="color: #ABB2BF">(str);</span></span>
<span class="line"><span style="color: #C678DD">short</span><span style="color: #E06C75"> a7 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #E5C07B">Short</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">parseShort</span><span style="color: #ABB2BF">(str);</span></span>
<span class="line"><span style="color: #C678DD">char</span><span style="color: #E06C75"> a8 </span><span style="color: #56B6C2">=</span><span style="color: #E06C75"> </span><span style="color: #E5C07B">str</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">charAt</span><span style="color: #ABB2BF">(</span><span style="color: #D19A66">0</span><span style="color: #ABB2BF">);</span><span style="color: #E06C75"> </span><span style="color: #7F848E; font-style: italic">// 将字符串第一个转为字符型</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="注意事项" tabindex="-1"><a class="header-anchor" href="#注意事项" aria-hidden="true">#</a> 注意事项！</h3>
<ol>
<li>在将 <strong>String</strong>  类型转成 基本数据类型时，要确保 <strong>String</strong> 类型能够转成有效的数据，比如 我们可以把“123”，转成一个整数，但是不能把 “hello” 转成一个整数</li>
<li>如果格式不正确，就会<strong>抛出异常</strong>，程序就会<strong>终止</strong>， 这个问题在异常处理章节中，会处理</li>
</ol>
</div></template>


