<template><div><h1 id="纯前端批量导出图片" tabindex="-1"><a class="header-anchor" href="#纯前端批量导出图片" aria-hidden="true">#</a> 纯前端批量导出图片</h1>
<!-- more -->
<p><code v-pre> npm install jszip --save</code></p>
<p><code v-pre>import JSZip from 'jszip'</code></p>
<div class="language-jsx line-numbers-mode" data-ext="jsx"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">    </span><span style="color: #61AFEF">downloadZip</span><span style="color: #ABB2BF">() {</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #C678DD">const</span><span style="color: #ABB2BF"> </span><span style="color: #E5C07B">zip</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">new</span><span style="color: #ABB2BF"> </span><span style="color: #61AFEF">JSZip</span><span style="color: #ABB2BF">()</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #61AFEF">setTimeout</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">_</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">          </span><span style="color: #7F848E; font-style: italic">/* 例：this.ArrayBase64 = [&quot;Base64字符串&quot;, &quot;Base64字符串&quot;, &quot;Base64字符串&quot;] */</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">ArrayBase64</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">forEach</span><span style="color: #ABB2BF">((</span><span style="color: #E06C75; font-style: italic">item</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75; font-style: italic">index</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #E5C07B">zip</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">file</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&#39;每个单独的文件名&#39;</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">+</span><span style="color: #ABB2BF"> </span><span style="color: #98C379">&#39;.png&#39;</span><span style="color: #ABB2BF">, </span><span style="color: #E5C07B">item</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">substring</span><span style="color: #ABB2BF">(</span><span style="color: #D19A66">22</span><span style="color: #ABB2BF">), { </span><span style="color: #E06C75">base64</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF"> })</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #7F848E; font-style: italic">/** 判断是否完成循环 */</span></span>
<span class="line"><span style="color: #ABB2BF">            </span><span style="color: #C678DD">if</span><span style="color: #ABB2BF"> (</span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #E5C07B">ArrayBase64</span><span style="color: #ABB2BF">.</span><span style="color: #E06C75">length</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">==</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">index</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">+</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">1</span><span style="color: #ABB2BF">) {</span></span>
<span class="line"><span style="color: #ABB2BF">              </span><span style="color: #E5C07B">zip</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">generateAsync</span><span style="color: #ABB2BF">({ </span><span style="color: #E06C75">type</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;blob&#39;</span><span style="color: #ABB2BF"> }).</span><span style="color: #61AFEF">then</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">content</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">                </span><span style="color: #E5C07B">FileSaver</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">saveAs</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75">content</span><span style="color: #ABB2BF">, </span><span style="color: #98C379">&#39;二维码.zip&#39;</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">              })</span></span>
<span class="line"><span style="color: #ABB2BF">            }</span></span>
<span class="line"><span style="color: #ABB2BF">        })</span></span>
<span class="line"><span style="color: #ABB2BF">      }, </span><span style="color: #D19A66">0</span><span style="color: #ABB2BF">)</span></span>
<span class="line"><span style="color: #ABB2BF">    },</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


