<template><div><h1 id="vue-中动态渲染组件以及传值" tabindex="-1"><a class="header-anchor" href="#vue-中动态渲染组件以及传值" aria-hidden="true">#</a> vue 中动态渲染组件以及传值</h1>
<!-- more -->
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">&lt;</span><span style="color: #E06C75">el-form-item</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">v-for</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;(item, index) in componentData&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">:key</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;index&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">:label</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;item.label&quot;</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">        &lt;</span><span style="color: #E06C75">component</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">:is</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&#39;item.component&#39;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">v-model</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;queryParams[item.field]&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">@keyup.enter.native</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;handleQuery&quot;</span><span style="color: #ABB2BF">&gt;&lt;/</span><span style="color: #E06C75">component</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">&lt;/</span><span style="color: #E06C75">el-form-item</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>使用 component 标签，is 属性中就是需要渲染的组件名</strong></p>
</div></template>


