<template><div><h1 id="vue-封装组件-使用-v-model-传递值" tabindex="-1"><a class="header-anchor" href="#vue-封装组件-使用-v-model-传递值" aria-hidden="true">#</a> vue 封装组件 使用 v-model 传递值</h1>
<!-- more -->
<h3 id="_1-子组件" tabindex="-1"><a class="header-anchor" href="#_1-子组件" aria-hidden="true">#</a> 1. 子组件</h3>
<div class="language-vue line-numbers-mode" data-ext="vue"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">&lt;</span><span style="color: #E06C75">template</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;</span><span style="color: #E06C75">el-select</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">v-model</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;equityId&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">placeholder</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;请选择权益名称&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">clearable</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">      &lt;</span><span style="color: #E06C75">el-option</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">v-for</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;(item, index) in equityNameList&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">:key</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;index&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">:label</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;item.equityName&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">:value</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;item.equityId&quot;</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">      &lt;/</span><span style="color: #E06C75">el-option</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;/</span><span style="color: #E06C75">el-select</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">&lt;/</span><span style="color: #E06C75">template</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">&lt;</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #C678DD">export</span><span style="color: #ABB2BF"> </span><span style="color: #C678DD">default</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #E06C75">name</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&quot;EquityNameList&quot;</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #61AFEF">data</span><span style="color: #ABB2BF">() {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #C678DD">return</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E06C75">equityId</span><span style="color: #ABB2BF">: </span><span style="color: #98C379">&#39;&#39;</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E06C75">equityNameList</span><span style="color: #ABB2BF">: []</span></span>
<span class="line"><span style="color: #ABB2BF">    }</span></span>
<span class="line"><span style="color: #ABB2BF">  },</span></span>
<span class="line"><span style="color: #ABB2BF">  </span><span style="color: #E06C75">watch</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E06C75">equityId</span><span style="color: #ABB2BF">: {</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #61AFEF">handler</span><span style="color: #ABB2BF">(</span><span style="color: #E06C75; font-style: italic">val</span><span style="color: #ABB2BF">) {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #E5C07B">this</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">$emit</span><span style="color: #ABB2BF">(</span><span style="color: #98C379">&quot;input&quot;</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75">val</span><span style="color: #ABB2BF">); </span><span style="color: #7F848E; font-style: italic">// 使用 input 传值</span></span>
<span class="line"><span style="color: #ABB2BF">      },</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E06C75">immediate</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">true</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E06C75">deep</span><span style="color: #ABB2BF">: </span><span style="color: #D19A66">false</span><span style="color: #ABB2BF">,</span></span>
<span class="line"><span style="color: #ABB2BF">    },</span></span>
<span class="line"><span style="color: #ABB2BF">  },</span></span>
<span class="line"><span style="color: #ABB2BF">}</span></span>
<span class="line"><span style="color: #ABB2BF">&lt;/</span><span style="color: #E06C75">script</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-父组件" tabindex="-1"><a class="header-anchor" href="#_2-父组件" aria-hidden="true">#</a> 2. 父组件</h3>
<div class="language-vue line-numbers-mode" data-ext="vue"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">&lt;</span><span style="color: #E06C75">el-form-item</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">label</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;权益名称&quot;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">prop</span><span style="color: #ABB2BF">=</span><span style="color: #98C379">&quot;equityId&quot;</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">    &lt;equity-name-list v-model=&quot;equityId&quot;&gt;&lt;/equity-name-list&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">&lt;/</span><span style="color: #E06C75">el-form-item</span><span style="color: #ABB2BF">&gt;</span></span>
<span class="line"><span style="color: #ABB2BF">import EquityNameList from &quot;@/components/Equity-name/index.vue&quot;</span></span>
<span class="line"><span style="color: #ABB2BF">  components: {</span></span>
<span class="line"><span style="color: #ABB2BF">    EquityNameList,</span></span>
<span class="line"><span style="color: #ABB2BF">  },</span></span>
<span class="line"><span style="color: #ABB2BF">  data() {</span></span>
<span class="line"><span style="color: #ABB2BF">    return { equityId: &quot;&quot; }</span></span>
<span class="line"><span style="color: #ABB2BF">  }</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>注：</strong> 子组件使用 input 传值， 父组件直接可以使用 v-model 接收子组件传过来的值，从而传递给 data 中，但是这种方式只适用于 form 表单中</p>
</div></template>


