export const data = JSON.parse("{\"key\":\"v-9dd68ef0\",\"path\":\"/vue-template-list/soybean-admin.html\",\"title\":\"Soybean Admin\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"Soybean Admin\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/spoony-z/vue-template-list/soybean-admin.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"SOBER\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Soybean Admin\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Soybean Admin\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"SOBER\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Soybean Admin\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"SOBER\\\",\\\"url\\\":\\\"https://github.com/spoony-Z\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"简介\",\"slug\":\"简介\",\"link\":\"#简介\",\"children\":[]},{\"level\":2,\"title\":\"特性\",\"slug\":\"特性\",\"link\":\"#特性\",\"children\":[]},{\"level\":2,\"title\":\"预览\",\"slug\":\"预览\",\"link\":\"#预览\",\"children\":[]},{\"level\":2,\"title\":\"文档\",\"slug\":\"文档\",\"link\":\"#文档\",\"children\":[]},{\"level\":2,\"title\":\"代码仓库\",\"slug\":\"代码仓库\",\"link\":\"#代码仓库\",\"children\":[]},{\"level\":2,\"title\":\"更新日志\",\"slug\":\"更新日志\",\"link\":\"#更新日志\",\"children\":[]},{\"level\":2,\"title\":\"后端服务\",\"slug\":\"后端服务\",\"link\":\"#后端服务\",\"children\":[]},{\"level\":2,\"title\":\"项目示例图\",\"slug\":\"项目示例图\",\"link\":\"#项目示例图\",\"children\":[]},{\"level\":2,\"title\":\"安装使用\",\"slug\":\"安装使用\",\"link\":\"#安装使用\",\"children\":[]},{\"level\":2,\"title\":\"Docker 部署\",\"slug\":\"docker-部署\",\"link\":\"#docker-部署\",\"children\":[]},{\"level\":2,\"title\":\"如何贡献\",\"slug\":\"如何贡献\",\"link\":\"#如何贡献\",\"children\":[]},{\"level\":2,\"title\":\"Git 贡献提交规范\",\"slug\":\"git-贡献提交规范\",\"link\":\"#git-贡献提交规范\",\"children\":[]},{\"level\":2,\"title\":\"浏览器支持\",\"slug\":\"浏览器支持\",\"link\":\"#浏览器支持\",\"children\":[]},{\"level\":2,\"title\":\"开源作者\",\"slug\":\"开源作者\",\"link\":\"#开源作者\",\"children\":[]},{\"level\":2,\"title\":\"交流\",\"slug\":\"交流\",\"link\":\"#交流\",\"children\":[]},{\"level\":2,\"title\":\"License\",\"slug\":\"license\",\"link\":\"#license\",\"children\":[]}],\"readingTime\":{\"minutes\":2.65,\"words\":796},\"filePathRelative\":\"vue-template-list/soybean-admin.md\",\"excerpt\":\"<h1> Soybean Admin</h1>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
