export const data = JSON.parse("{\"key\":\"v-485200df\",\"path\":\"/vue-template-list/vue-next-admin.html\",\"title\":\"vue-next-admin\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"vue-next-admin\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/spoony-z/vue-template-list/vue-next-admin.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"SOBER\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"vue-next-admin\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"vue-next-admin\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"SOBER\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"vue-next-admin\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"SOBER\\\",\\\"url\\\":\\\"https://github.com/spoony-Z\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"🌈 介绍\",\"slug\":\"🌈-介绍\",\"link\":\"#🌈-介绍\",\"children\":[]},{\"level\":2,\"title\":\"⛱️ 线上预览\",\"slug\":\"⛱️-线上预览\",\"link\":\"#⛱️-线上预览\",\"children\":[]},{\"level\":2,\"title\":\"💒 代码仓库\",\"slug\":\"💒-代码仓库\",\"link\":\"#💒-代码仓库\",\"children\":[]},{\"level\":2,\"title\":\"🚧 安装 cnpm、yarn\",\"slug\":\"🚧-安装-cnpm、yarn\",\"link\":\"#🚧-安装-cnpm、yarn\",\"children\":[]},{\"level\":2,\"title\":\"🏭 环境支持\",\"slug\":\"🏭-环境支持\",\"link\":\"#🏭-环境支持\",\"children\":[]},{\"level\":2,\"title\":\"⚡ 使用说明\",\"slug\":\"⚡-使用说明\",\"link\":\"#⚡-使用说明\",\"children\":[]},{\"level\":2,\"title\":\"📚 开发文档\",\"slug\":\"📚-开发文档\",\"link\":\"#📚-开发文档\",\"children\":[]},{\"level\":2,\"title\":\"💯 学习交流加 QQ 群\",\"slug\":\"💯-学习交流加-qq-群\",\"link\":\"#💯-学习交流加-qq-群\",\"children\":[]},{\"level\":2,\"title\":\"💒 集成后端\",\"slug\":\"💒-集成后端\",\"link\":\"#💒-集成后端\",\"children\":[]},{\"level\":2,\"title\":\"❤️ 鸣谢列表\",\"slug\":\"❤️-鸣谢列表\",\"link\":\"#❤️-鸣谢列表\",\"children\":[]},{\"level\":2,\"title\":\"💕 特别感谢\",\"slug\":\"💕-特别感谢\",\"link\":\"#💕-特别感谢\",\"children\":[]}],\"readingTime\":{\"minutes\":3.57,\"words\":1070},\"filePathRelative\":\"vue-template-list/vue-next-admin.md\",\"excerpt\":\"<h1> vue-next-admin</h1>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
