export const data = JSON.parse("{\"key\":\"v-2940ada0\",\"path\":\"/vue-template-list/vue-element-admin.html\",\"title\":\"vue-element-admin\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"vue-element-admin\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/spoony-z/vue-template-list/vue-element-admin.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"SOBER\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"vue-element-admin\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"vue-element-admin\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"SOBER\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"vue-element-admin\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"SOBER\\\",\\\"url\\\":\\\"https://github.com/spoony-Z\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"简介\",\"slug\":\"简介\",\"link\":\"#简介\",\"children\":[]},{\"level\":2,\"title\":\"前序准备\",\"slug\":\"前序准备\",\"link\":\"#前序准备\",\"children\":[]},{\"level\":2,\"title\":\"Sponsors\",\"slug\":\"sponsors\",\"link\":\"#sponsors\",\"children\":[{\"level\":3,\"title\":\"Akveo\",\"slug\":\"akveo\",\"link\":\"#akveo\",\"children\":[]},{\"level\":3,\"title\":\"Flatlogic\",\"slug\":\"flatlogic\",\"link\":\"#flatlogic\",\"children\":[]}]},{\"level\":2,\"title\":\"功能\",\"slug\":\"功能\",\"link\":\"#功能\",\"children\":[]},{\"level\":2,\"title\":\"开发\",\"slug\":\"开发\",\"link\":\"#开发\",\"children\":[]},{\"level\":2,\"title\":\"发布\",\"slug\":\"发布\",\"link\":\"#发布\",\"children\":[]},{\"level\":2,\"title\":\"其它\",\"slug\":\"其它\",\"link\":\"#其它\",\"children\":[]},{\"level\":2,\"title\":\"Changelog\",\"slug\":\"changelog\",\"link\":\"#changelog\",\"children\":[]},{\"level\":2,\"title\":\"Online Demo\",\"slug\":\"online-demo\",\"link\":\"#online-demo\",\"children\":[]},{\"level\":2,\"title\":\"购买贴纸\",\"slug\":\"购买贴纸\",\"link\":\"#购买贴纸\",\"children\":[]},{\"level\":2,\"title\":\"Browsers support\",\"slug\":\"browsers-support\",\"link\":\"#browsers-support\",\"children\":[]},{\"level\":2,\"title\":\"License\",\"slug\":\"license\",\"link\":\"#license\",\"children\":[]}],\"readingTime\":{\"minutes\":5.02,\"words\":1505},\"filePathRelative\":\"vue-template-list/vue-element-admin.md\",\"excerpt\":\"<h1> vue-element-admin</h1>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
