<template><div><h1 id="数组中的-some-方法" tabindex="-1"><a class="header-anchor" href="#数组中的-some-方法" aria-hidden="true">#</a> 数组中的 some 方法</h1>
<!-- more -->
<h3 id="使用场景" tabindex="-1"><a class="header-anchor" href="#使用场景" aria-hidden="true">#</a> <strong>使用场景</strong> ：</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="shiki one-dark-pro" style="background-color: #282c34" tabindex="0"><code><span class="line"><span style="color: #ABB2BF">      </span><span style="color: #C678DD">let</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">arr</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">=</span><span style="color: #ABB2BF"> [</span><span style="color: #D19A66">1</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">2</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">3</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">4</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">5</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">6</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">7</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">8</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">9</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">10</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">11</span><span style="color: #ABB2BF">,</span><span style="color: #D19A66">12</span><span style="color: #ABB2BF">]</span></span>
<span class="line"><span style="color: #ABB2BF">      </span><span style="color: #E5C07B">arr</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">some</span><span style="color: #ABB2BF">((</span><span style="color: #E06C75; font-style: italic">value</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75; font-style: italic">index</span><span style="color: #ABB2BF">, </span><span style="color: #E06C75; font-style: italic">arr</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> {</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #7F848E; font-style: italic">// console.log(value, index, arr);</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #7F848E; font-style: italic">// 1 0 (12) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #7F848E; font-style: italic">// 2 1 (12) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #7F848E; font-style: italic">// 3 2 (12) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #7F848E; font-style: italic">// 4 3 (12) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]</span></span>
<span class="line"><span style="color: #ABB2BF">        </span><span style="color: #7F848E; font-style: italic">// ......</span></span>
<span class="line"><span style="color: #ABB2BF">      })</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #7F848E; font-style: italic">// 数组中若满足条件，返回 true 且只返回一次</span></span>
<span class="line"><span style="color: #ABB2BF">    </span><span style="color: #E5C07B">arr</span><span style="color: #ABB2BF">.</span><span style="color: #61AFEF">some</span><span style="color: #ABB2BF">((</span><span style="color: #E06C75; font-style: italic">value</span><span style="color: #ABB2BF">) </span><span style="color: #C678DD">=&gt;</span><span style="color: #ABB2BF"> </span><span style="color: #E06C75">value</span><span style="color: #ABB2BF"> </span><span style="color: #56B6C2">&gt;</span><span style="color: #ABB2BF"> </span><span style="color: #D19A66">5</span><span style="color: #ABB2BF">) </span><span style="color: #7F848E; font-style: italic">// true</span></span>
<span class="line"><span style="color: #ABB2BF">    </span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


